name: 'Azure Artifact Feed NPM Authenticate'
description: 'Generate an .npmrc file for azure authentication'
inputs:
  organization:
    description: 'Your Azure organization'
    required: true
  registry:
    description: "Your Azure registry"
    required: true
  user:
    description: "Your Azure user"
    required: false
    default: githubaction
  password:
    description: "Your Azure password"
    required: true
  email:
    description: "Your Azure email"
    required: false
    default: githubaction@farohealth.com

runs:
  using: "composite"
  steps:
    - id: set_vars
      shell: bash
      run: |
        echo "azure_url=pkgs.dev.azure.com/${{ inputs.organization }}/_packaging/${{ inputs.registry }}/npm" >> $GITHUB_OUTPUT
    - shell: bash
      run: |
        echo "registry=https://${{ steps.set_vars.outputs.azure_url }}/registry/" > ~/.npmrc
        echo "always-auth=true" >> ~/.npmrc
        echo "; begin auth token" >> ~/.npmrc
        echo "//${{ steps.set_vars.outputs.azure_url }}/registry/:username=${{ inputs.user }}" >> ~/.npmrc
        echo '//${{ steps.set_vars.outputs.azure_url }}/registry/:_password="${{ inputs.password}}"' >> ~/.npmrc
        echo '//${{ steps.set_vars.outputs.azure_url }}/registry/:email=${{ inputs.email }}' >> ~/.npmrc
        echo '//${{ steps.set_vars.outputs.azure_url }}/:username=${{ inputs.user }}' >> ~/.npmrc
        echo '//${{ steps.set_vars.outputs.azure_url }}/:_password="${{ inputs.password }}"' >> ~/.npmrc
        echo '//${{ steps.set_vars.outputs.azure_url }}/:email=${{ inputs.email }}' >> ~/.npmrc
        echo '; end auth token' >> ~/.npmrc
