name: 'Notify slack action'
description: 'Notifies slack channel about builds'
inputs:
  owner:
    description: 'Owner of the repo'
    required: true
  repo:
    description: 'Name of the repo'
    required: true
  message:
    description: 'Message to show'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
runs:
  using: 'node16'
  main: 'index.js'