name: 'Build and test'
description: 'Lint, build, test and generate coverage report'

runs:
  using: "composite"
  steps:
    - run: ls -al
      shell: bash
    - run: npm ci
      shell: bash
    - run: npm run lint
      shell: bash
    - run: npm run build
      shell: bash
    - run: npm run coverage:c
      shell: bash
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: test-output/test-results.xml
    - name: Publish Cobertura coverage results
      uses: 5monkeys/cobertura-action@master
      if: ${{ github.event_name != 'workflow_dispatch' }}
      with:
        path: coverage-report/cobertura-coverage.xml
        report_name: Code Coverage
        show_line: true
        fail_below_threshold: false
        minimum_coverage: 50
