name: 'Build and test'
description: 'Lint, build, test and generate coverage report'

inputs:
  minimum-coverage:
    required: false
    default: 50
    description: 'The minimum allowed coverage percentage as an integer.'
  test-report-path:
    required: false
    default: 'test-results.xml'
    description: 'The path to the test report.'
  coverage-report-path:
    required: false
    default: 'cobertura-coverage.xml'
    description: 'The path to the coverage report.'

runs:
  using: "composite"
  steps:
    - run: ls -al
      shell: bash
    - run: npm ci
      shell: bash
    - run: npm run lint
      shell: bash
    - run: npm run build
      shell: bash
    - run: npm run coverage:ci
      shell: bash
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: ${{inputs.test-report-path}}
    - name: Publish Cobertura coverage results
      uses: 5monkeys/cobertura-action@master
      if: ${{ github.event_name != 'workflow_dispatch' }}
      with:
        path: ${{inputs.coverage-report-path}}
        report_name: Code Coverage
        show_line: true
        fail_below_threshold: false
        minimum_coverage: ${{ inputs.minimum-coverage }}
