name: 'Set up npm and node'
description: 'Initialize npm and node versions and authentication'

inputs:
  node-version:
    required: false
    default: '18'
    description: 'Node version'
  npm-token:
    required: true
    description: 'Authentication token to connect to Azure Artifact Feed'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Azure DevOps NPM
      uses: Faro-Health/github-actions/azure-devops-npm@master
      with:
        organization: farohealth
        registry: faro-common-libs
        password: ${{ inputs.npm-token }}
