name: 'Docker build and publish'
description: 'tbd'

inputs:
  inputs:
    target_image_name:
      required: true
    registry_login_server:
      required: true
    registry_username:
      required: true
    registry_password:
      required: true
    app-name:
      required: true

runs:
  using: "composite"
  steps:
    - name: 'Connect to docker registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ inputs.registry_login_server }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}
    - name: 'Build and push docker image'
      run: |
        cp ~/.npmrc `pwd`/docker/.npmrc
        docker build ./docker -t ${{ inputs.registry_login_server }}/${{ inputs.target_image_name }}:${{ inputs.version }} -t  ${{ inputs.registry_login_server }}/${{ inputs.target_image_name }}:latest
        docker push -a ${{ inputs.registry_login_server }}/${{ inputs.target_image_name }}
      shell: bash
    - name: Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.app-name }}
        images: ${{ inputs.registry_login_server }}/${{ inputs.target_image_name }}:${{ env.version }}

