name: 'NodeJS Service Docker build and publish'
description: 'Docker build and publish for Node-based API service containers'

inputs:
  version:
    required: true
    description: 'The image version/tag'
  target-image-name:
    required: true
    description: 'The image name'
  registry-login-server:
    required: true
    description: 'Docker registry server'
  registry-username:
    required: true
    description:  'Docker registry server user name'
  registry-password:
    required: true
    description:  'Docker registry server user password'
  working-directory:
    required: false
    default: '.'
    description: 'Working directory without trailing slash'

runs:
  using: "composite"
  steps:
    - name: 'Connect to docker registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ inputs.registry-login-server }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}
    - name: 'Build and push docker image'
      run: |
        cp ~/.npmrc `pwd`/docker/.npmrc
        docker build ./docker -t ${{ inputs.registry-login-server }}/${{ inputs.target-image-name }}:${{ inputs.version }} -t  ${{ inputs.registry-login-server }}/${{ inputs.target-image-name }}:latest
        docker push -a ${{ inputs.registry-login-server }}/${{ inputs.target-image-name }}
      env:
        VERSION: ${{ inputs.version }}
      shell: bash
      working-directory: ${{inputs.working-directory}}

