name: 'Docker build and publish'
description: 'Docker build and publish'

inputs:
  last_status:
    required: true
    description: 'Workflow last run status'
  current_status:
    required: true
    description: 'Workflow current run status'

runs:
  using: "composite"
  steps:
    - name: Build fixed slack message
      uses: rtCamp/action-slack-notify@v2.1.3
      if: ${{ success() && steps.last_status.outputs.last_status == 'failure' }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'Style check fixed now!'

    - name: Build faile slack message
      uses: rtCamp/action-slack-notify@v2.1.3
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'Failure'

