name: 'Docker build and publish'
description: 'Docker build and publish'

inputs:
  last_status:
    required: true
    description: 'Workflow last run status: success or failure'
  current_status:
    required: true
    description: 'Workflow current run status: success or failure'
  slack-webhook:
    required: true
    description: 'Slack webhook'

runs:
  using: "composite"
  steps:
    - name: Build fixed slack message
      uses: rtCamp/action-slack-notify@v2.1.3
      if: ${{ inputs.current_status == 'success' && inputs.last_status  == 'failure' }}
      env:
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        SLACK_MESSAGE: 'Style check fixed now!'
        SLACK_CHANNEL: 'ci-failure'
        SLACK_ICON: ':white_check_mark:'

    - name: Build faile slack message
      uses: rtCamp/action-slack-notify@v2.1.3
      if: ${{ inputs.current_status == 'failure' }}
      env:
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        SLACK_MESSAGE: 'Failure'
        SLACK_CHANNEL: 'ci-failure'
        SLACK_ICON: ':octagonal_sign:'

