name: 'Docker build and publish'
description: 'Docker build and publish'

inputs:
  last-status:
    required: true
    description: 'Workflow last run status: success or failure'
  slack-webhook:
    required: true
    description: 'Slack webhook'

runs:
  using: "composite"
  steps:
    - name: Get current workflow status
      uses: martialonline/workflow-status@v3
      if: always()
      id: workflow-status

    - name: Build fixed slack message
      uses: rtCamp/action-slack-notify@v2.1.3
      if: ${{ steps.workflow-status.outputs.status == 'success' && inputs.last-status  == 'failure' }}
      env:
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        SLACK_MESSAGE: 'Fixed now!'
        SLACK_CHANNEL: 'ci-failure'
        SLACK_ICON_EMOJI: ':white_check_mark:'
        SLACK_USERNAME: 'GitHubAction'
        SLACK_COLOR: ${{ steps.workflow-status.outputs.status }}

    - name: Build faile slack message
      uses: rtCamp/action-slack-notify@v2.1.3
      if: ${{ steps.workflow-status.outputs.status == 'failure' }}
      env:
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        SLACK_MESSAGE: 'Failed build'
        SLACK_CHANNEL: 'ci-failure'
        SLACK_ICON_EMOJI: ':octagonal_sign:'
        SLACK_USERNAME: 'GitHubAction'
        SLACK_COLOR: ${{ steps.workflow-status.outputs.status }}

