name: 'Version and push'
description: 'Bump package.json version to next pre-release and push commit to git'

inputs:
  working-directory:
    required: true
    description: 'Working directory.'
  module-name:
    required: true
    description: 'Module name.'

outputs:
  version:
    description: "Newly created prerelease version"
    value: ${{ steps.prerelease-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: git set your account's default identity.
      run: |
        git config --global user.email "ci.build@farohealth.com"
        git config --global user.name "CI Build"
      shell: bash
      working-directory: ${{inputs.working-directory}}

    - run: npm run prerelease:version
      shell: bash
      working-directory: ${{inputs.working-directory}}

    - id: prerelease-version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{inputs.working-directory}}

    - name: Git commit with message
      shell: bash
      run: |
        git add package.json package-lock.json
        export GIT_MESSAGE="Upgrade ${{inputs.module-name}} to ${{ steps.prerelease-version.outputs.version }} during CI [skip ci]"
        git commit -m "$GIT_MESSAGE"
        git pull --ff --no-edit && git push origin
      working-directory: ${{inputs.working-directory}}


