name: 'Version and push'
description: 'Bump package.json version to next pre-release and push commit to git'

inputs:
  working-directory:
    required: false
    default: '.'
    description: 'Working directory without trailing slash'
  ghToken:
    required: true
    description: 'Github Token'

outputs:
  version:
    description: "Final assigned prerelease version"
    value: ${{ steps.prerelease-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: git set your account's default identity.
      run: |
        git config --global user.email "ci.build@farohealth.com"
        git config --global user.name "CI Build"
      shell: bash
      working-directory: ${{inputs.working-directory}}
    - run: npm run prerelease:version
      shell: bash
      working-directory: ${{inputs.working-directory}}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      working-directory: ${{inputs.working-directory}}
    - name: merge
      uses: buildsville/simple-merge@v1
      with:
        token: ${{ inputs.ghToken }}
        method: 'merge'
        title: 'Version bump'
        message: 'Bumping Version Merge'
    - id: prerelease-version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{inputs.working-directory}}
    - id: prerelease-version
      run: echo "package_name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{inputs.working-directory}}
