name: 'Version and publish'
description: 'Version and publish'

outputs:
  version:
    description: "Prerelease version"
    value: ${{ steps.prerelease-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: git set your account's default identity.
      run: |
        git config --global user.email "ci.build@farohealth.com"
        git config --global user.name "CI Build"
      shell: bash
    - run: npm run prerelease:version
      shell: bash
    - run: git pull --ff --no-edit && git push
      shell: bash
    - id: prerelease-version
      run:   echo "version=$(node -p "require('./package.json').version")" >> GITHUB_OUTPUT
      shell: bash
