name: 'Version and push'
description: 'Bump package.json version to next pre-release and push commit to git'

inputs:
  working-directory:
    required: false
    default: '.'
    description: 'Working directory without trailing slash'
  ghtoken:
    required: true
    description: 'Github Token'

outputs:
  version:
    description: "Final assigned prerelease version"
    value: ${{ steps.prerelease-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: git set your account's default identity.
      run: |
        git config --global user.email "ci.build@farohealth.com"
        git config --global user.name "CI Build"
      shell: bash
      working-directory: ${{inputs.working-directory}}
    - run: npm run prerelease:version
      shell: bash
      working-directory: ${{inputs.working-directory}}

    - name: Create Pull Request
      id: pr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{inputs.ghtoken}}

    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        number: ${{ steps.pr.outputs.pull-request-number }}
        github-token: ${{inputs.ghtoken}}
        method: squash

    - name: Set output
      run: |
        echo "$(node -p "require('./package.json').version")";
        echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT;
        echo "bleh='meh'" >> $GITHUB_OUTPUT;
      shell: bash
      working-directory: ${{inputs.working-directory}}
    - name: Set output
      run: |
        echo "$(node -p "require('./package.json').name")";
        echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT;
      shell: bash
      working-directory: ${{inputs.working-directory}}
