name: 'update-versions-manifest'
description: 'updates current versions manifest with latest deployed version'

inputs:
  filename:
    required: true
    description: 'Deployed environment'
  newversions:
    required: true
    description: 'escaped json representing a dictionary of new Versions deployed to a specific environment'
  manifestrepo:
    required: true
    description: 'repo of manifest files'
  manifestreporef:
    required: true
    description: 'branch ref for manifests file repo'
  gitemail:
    description: 'git account email'
    required: true
  gitusername:
    required: true
    description: 'git account username'
  ghtoken:
    required: true
  replaceall:
    required: false
    description: 'flag to replaceentire contents of selected file'

runs:
  using: "composite"
  steps:
    - name: Create subdirectory
      shell: bash
      run: |
        pwd
        ls
        mkdir ~/manifests
        ls
        cd /manifests
        ls
    - name: Set default git identity.
      shell: bash
      run: |
        git init
        git config user.email "${{ inputs.gitemail }}"
        git config user.name "${{ inputs.gitusername }}"
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        repository: ${{ inputs.manifestrepo }}
        ref:  ${{ inputs.manifestreporef }}
        token: ${{ inputs.ghtoken }}
        path: /manifests
    - name: Update manifest
      if: ${{ inputs.replaceall != 'true' }}
      shell: bash
      run: |
        jq --arg versions ${{ inputs.newversions }} '. * ($versions | fromjson)' ${{inputs.filename}} > ${{inputs.filename}}.tmp && mv ${{inputs.filename}}.tmp ${{inputs.filename}}
    - name: Update manifest
      if: ${{ inputs.replaceall == 'true' }}
      shell: bash
      run: |
        echo ${{ fromJSON(inputs.newversions) }} > ${{inputs.filename}}
    - name: Push to repo
      shell: bash
      run: |
        git add .
        git commit -m "version manifest update $(date) [skip ci]"
        git push
    - name: Cleanup
      shell: bash
      run: |
        cd ../
        rm -rf ./manifests

