name: 'generate-versions-map'
description: 'creates a version map escaped json string for a single application to be used with update-versions-manifest'

inputs:
  module-name:
    required: true
    description: 'name of app to update'
  version:
    required: true
    description: 'new version of app'
  repository:
    required: true
    description: 'repository of app'

outputs:
  versionmap:
    description: "Map of info for current version"
    value: ${{ steps.version-map.outputs.versionmap }}

runs:
  using: "composite"
  steps:
    - name: Update manifest
      id: version-map
      shell: bash
      run: |
        versionmap=$(echo -n '{ "${{ inputs.module-name }}" : { "version": "${{ inputs.version }}", "repo": "${{ inputs.repository }}" } }' | jq -Rsa)
        echo $versionmap
        echo "versionmap=$versionmap" >> $GITHUB_OUTPUT
