name: 'generate-versions-map'
description: 'creates a version map escaped json string for a single application to be used with update-versions-manifest'

inputs:
  app-name:
    required: true
    description: 'name of app to update'
  version:
    required: true
    description: 'new version of app'
  repository:
    required: true
    description: 'repository of app'

runs:
  using: "composite"
  steps:
    - name: Update manifest
      shell: bash
      run: |
        echo "map=$(echo -n '{
              "${{ inputs.app-name }}" : {
                version: "${{ inputs.version }}",
                repo: "${{ inputs.repository }}",
              }
            }' | jq -Rsa)" >> $GITHUB_OUTPUT
